version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 

     # build image
     - run: |
         docker info
         docker build -t aspnetapp -f Dockerfile .
     # deploy the image
     - run: |
         docker login --username=$lkostoprav@gmail.com --password=$2e5e126b-9169-460d-bd20-2eedb2fa477e registry.heroku.com
         docker tag aspnetapp registry.heroku.com/$carhistoryvin/web
         docker push registry.heroku.com/$carhistoryvin/web                
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku container:release web -a $carhistoryvin