version: 2

 jobs:
   build:
     ...
   deploy:
     docker:
       - image: deadapolon/carhistory:latest
     steps:
       - checkout
       - run:
           name: Deploy Master to Heroku
           command: |
             git push https://heroku:$2e5e126b-9169-460d-bd20-2eedb2fa477e@git.heroku.com/$carhistory.git master

 workflows:
   version: 2
   build-deploy:
     jobs:
       - build
       - deploy:
           requires:
             - build # only run deploy-via-git job if the build job has completed
           filters:
             branches:
               only: master # only run deploy-via-git job on master branch